# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2118a452b1a48dccc2776237425399a44128ca37a47d1a273f8e5337311b1e5480b8f98f680223285228ed54d5ccd0f84813b1a443f8adc6af2b07a543c6b2cb

test:
  secret_key_base: 8aee7b398f9ec78782451438f4b74aca0972b0723c9349bf4b80fdaf47d951e558b7d19927b076aafe68357a357134e19ee9e8240d0561f5683b1ba022a10334

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
